🐍 python:
  - "**/*.py"
  - "*.py" 

📝 documentation:
  - "**/*.md"
  - "*.md"

🐳 docker:
  - "Dockerfile"

⚙ ci:
  - ".github/**"
  
 hacktoberfest-accepted:
  - C/**/*
  - CPP/**/*
  - Python/**/*
  - Java/**/*
