hacktoberfest-accepted:
  - "*"
  - "C/*.c"
  - "CPP/*.cpp"
  - "Python/*.py"
  
🐍 python:
  - "**/*.py"
  - "*.py"
  
cpp:
  - "**/*.cpp"
  - "*.cpp"
c:
  - "**/*.c"
  - "*.c"
java:
  - "**/*.java"
  - "*.java"


📝 documentation:
  - "**/*.md"
  - "*.md"

🐳 docker:
  - "Dockerfile"

⚙ ci:
  - ".github/**"
